### ISSUE TITLE
springboot3.x (17, 3.1.4  -Dspring-framework.version=6.0.12)  UT failed.

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata#6051]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://github.com/seata/seata/assets/8758457/d8fb29a0-a679-483e-a3b0-4943cd3dc4e4)
https://github.com/seata/seata/actions/runs/6901808630/job/18792798232

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
![image](https://github.com/seata/seata/assets/19943636/23cf5542-98b4-4822-8a66-302b14cc951e)
可能是因为snakeyaml单独指定了版本号,导致没有跟随springboot的版本号变化而变化,导致引起这个问题
Maybe because snakeyaml separately specified the version number, which does not follow the springboot version number change and change, resulting in this problem
