### ISSUE TITLE
TMClient's nettyClientKeyPool doesn't work as it should

### ISSUE THREAD

**Issue by PleaseGiveMeTheCoke** [apache/incubator-seata#6142]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在NettyClientChannelManager的doConnect方法中，每次都会创建一个新的NettyPoolKey。如果是TMClient的话，会直接调用poolKeyMap.put而不是像RMClient一样的poolKeyMap.putIfAbsent，这会导致每次poolKeyMap中serverAddress对应的NettyPoolKey都会被更新。而下面的nettyClientKeyPool.borrowObject每次都会使用到这一更新后的NettyPoolKey作为key去池子中获取对象，这相当于每次都使用一个新的池子来新建对象，丧失了缓存池的意义

---

In the doConnect method of the NettyClientChannelManager, a new NettyPoolKey is created each time. if it is a TMClient, it will directly call poolKeyMap.put instead of poolKeyMap.putIfAbsent like RMClient. putIfAbsent, which will result in the NettyPoolKey corresponding to the serverAddress in the poolKeyMap being updated every time. The following nettyClientKeyPool.borrowObject will use this updated NettyPoolKey as the key to get the object in the pool every time, which is equivalent to using a new pool to create new objects every time, which loses the meaning of the cache pool.

![image](https://github.com/seata/seata/assets/77573225/736e31a2-35ec-4ca5-b80d-81fdb42eef46)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
我个人的理解是`rm`的`RegisterRMRequest`是可以服用,并且更新`resourceid`列表,比如一个`client`拥有一个动态的数据源,那么就可能导致`RegisterRMRequest`中的resourceid增删,所以在`rm`中`NettyPoolKey`的`message`是可以被复用的,而TM则不同,在使用`TmNettyRemotingClient#getInstance`时,是可以修改他的`applicationId`和`transactionServiceGroup`,也就导致了每一次进行`doconnect`就会需要诞生一条新的RegisterTMRequest,所以tm与rm的逻辑上不同. 但是这段代码看起来确实存在一定有优化空间, 使其可读性增加,比如我认为为了让两者共有一个`NettyClientChannelManager`,导致代码用了比较粗糙的`if else`,在`doconnect`上是否能够分离开? 即便不能我也认为rm不应该为了tm必须构建一条新的`RegisterTMRequest`,而每次都要创建一个用不上的`RegisterRMRequest`, 当然欢迎社区有其它不同理解的同学一起发表意见. 也邀请这些核心逻辑的作者 @slievrly 帮我们确认这个问题.

My personal understanding is that the'RegisterRMRequest 'of'rm' can be taken, and the'resourceid 'list is updated. For example, if a'client' has a dynamic data source, it may cause the resourceid in'RegisterRMRequest 'to be added or deleted. Therefore, the'message' of'NettyPoolKey 'in'rm' can be reused, while TM is different. When using 'TmNettyRemotingClient #getInstance ', you can modify its'applicationId' and 'transactionServiceGroup ', which will lead to the need to generate a new RegisterTMRequest every time you perform'doconnect', so the logic of tm and rm is different. 
But this code does seem to have room for optimization to increase its legibility. For example, I think that in order to make the two have a 'NettyClientChannelManager ', the code uses a relatively rough'if else'. Can it be separated on'doconnect '? Even if not, I don't think rm should create a'RegisterRMRequest' every time for tm to have to build a new'RegisterTMRequest '. Of course, students from the community with different understandings are welcome to express their opinions. Also invite the author of these core logics @slievrly to help us confirm this problem.

**Comment by slievrly** [comment]
@PleaseGiveMeTheCoke @funky-eyes  I've reviewed the existing code, and there is indeed an issue with the TmNettyRemotingClient creating a new object for the same serverAddress each time. This certainly leads to a new poolList being opened every time in the connection pool. Thank you @PleaseGiveMeTheCoke for the feedback, and I welcome you to propose a viable modification plan, so we can discuss it further.

**Comment by PleaseGiveMeTheCoke** [comment]
How about this, which is a very simple approach @slievrly @funky-eyes 
```
    private Channel doConnect(String serverAddress) {
        Channel channelToServer = channels.get(serverAddress);
        if (channelToServer != null && channelToServer.isActive()) {
            return channelToServer;
        }
        Channel channelFromPool;
        try {
            NettyPoolKey currentPoolKey = poolKeyFunction.apply(serverAddress);
            NettyPoolKey previousPoolKey = poolKeyMap.putIfAbsent(serverAddress, currentPoolKey);
            if(previousPoolKey != null){
                if (currentPoolKey.getMessage() instanceof RegisterTMRequest) {
                    RegisterTMRequest registerTMRequest = (RegisterTMRequest) currentPoolKey.getMessage();
                    ((RegisterTMRequest) previousPoolKey.getMessage()).setTransactionServiceGroup(registerTMRequest.getTransactionServiceGroup());
                    ((RegisterTMRequest) previousPoolKey.getMessage()).setApplicationId(registerTMRequest.getApplicationId());
                    ((RegisterTMRequest) previousPoolKey.getMessage()).setExtraData(registerTMRequest.getExtraData());
                } else {
                    RegisterRMRequest registerRMRequest = (RegisterRMRequest) currentPoolKey.getMessage();
                    ((RegisterRMRequest) previousPoolKey.getMessage()).setResourceIds(registerRMRequest.getResourceIds());
                }
            }
            channelFromPool = nettyClientKeyPool.borrowObject(poolKeyMap.get(serverAddress));
            channels.put(serverAddress, channelFromPool);
        } catch (Exception exx) {
            LOGGER.error("{} register RM failed.", FrameworkErrorCode.RegisterRM.getErrCode(), exx);
            throw new FrameworkException("can not register RM,err:" + exx.getMessage());
        }
        return channelFromPool;
    }
```

**Comment by slievrly** [comment]
@PleaseGiveMeTheCoke I still think the solution might be a bit complex. Since NettyPoolKey is specifically used to obtain keys for connection pool objects, could we rewrite its hashCode method to ignore unnecessary attributes? Do you think it's reasonable?
