### ISSUE TITLE
seata server优雅下线方案实现

### ISSUE THREAD

**Issue by yearnxiao** [apache/incubator-seata#6500]
## Why you need it?
seata server优雅下线方案。

## How it could be?
在k8s生产环境进行seata server服务维护或升级时，就会遇到客户端频繁报无法连接服务端的报错，导致服务不可用，每次都需要手动重启所有客户端服务来恢复业务。希望官方能提供一个有效的服务端优雅下线方案。

## Other related information
客户端报错信息如下：
dsn-front-6888dcbdb8-k7swb-prod
0101 can not connect to 10.244.22.79:8091 cause:can not register RM,err:can not connect to services-server.io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:225)
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:107)
	at io.seata.core.rpc.netty.NettyClientChannelMana

dsn-front-6888dcbdb8-k7swb-prod
0304 register RM failed.io.seata.common.exception.FrameworkException: can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientBootstrap.getNewChannel(NettyClientBootstrap.java:182)
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:58)
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectP

**Comment by funky-eyes** [comment]
用的clusterip？或者svc 域名？
Use clusterip? Or svc domain name?

**Comment by yearnxiao** [comment]
用的就是svc域名，但客户端调用时是去nacos注册中心拉取所有sever的pod ip来进行业务调用的

**Comment by yearnxiao** [comment]
> 用的clusterip？或者svc 域名？ Use clusterip? Or svc domain name?

用的就是svc域名，但客户端调用时是去nacos注册中心拉取所有sever的pod ip来进行业务调用的

**Comment by funky-eyes** [comment]
那你应该遇到的是1.5以后得bug，这个bug导致优雅下线失效了，这个问题将在1.8.1和2.1上被修复。
原因是由于seata-server有一个10s自检的的线程，它会将所有从注册中心的连接进行检查，检查后才放入可使用列表，也就是这个列表的时间一直是滞后注册中心10s，然后seata-server的优雅下线时的等待时间只有3s，导致请求时拿到了已经下线的seata-server地址引发的这个问题。
The bug you encountered, which affects graceful shutdown, is expected to be fixed in versions 1.8.1 and 2.1. This issue arises from a bug introduced after version 1.5.

The root cause lies in a 10-second self-checking thread in the Seata server. This thread verifies all connections from the registry center and only adds them to the available list after the check. Consequently, the time in this list lags behind the registry center by 10 seconds. The graceful shutdown feature of Seata server has a wait time of only 3 seconds, leading to requests receiving the address of the Seata server, which has already been taken offline, thereby causing the issue.

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/pull/6143

**Comment by yearnxiao** [comment]
> #6143

好的，谢谢！我们再关注下后续版本。
