### ISSUE TITLE
抽象一个数据库适配模块，各种数据库的适配支持通过增加适配器的方式实现

### ISSUE THREAD

**Issue by zerowindy** [apache/incubator-seata#6528]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
抽象一个数据库适配模块，各种数据库的适配支持通过增加适配器的方式实现，这样可以在新增适配一个新类型的数据库的时候，不需要大版本更新，只需要新增一个适配器即可实现。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by funky-eyes** [comment]
本来就可以通过spi的方式扩展数据库支持。但是由于有 https://github.com/apache/incubator-seata/issues/5781 这个bug导致无法自行扩展实现，必须编译seata-all源码进行扩展
It is possible to extend database support through spi. However, due to the bug #5781, the implementation cannot be extended by itself, and the seata-all source code must be compiled for extension
