### ISSUE TITLE
请问 2.1.0 要多久才能正式发布 已经RC好久了 不知道啥时候能用上

### ISSUE THREAD

**Issue by JavaLionLi** [apache/incubator-seata#6635]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by xingfudeshi** [comment]
Thank you for your interest in Apache Seata(incubating). Currently, rc4 is in the voting stage, and any updates will be posted in the dev mailing list. You can subscribe to the mailing list to stay updated. dev-subscribe@seata.apache.org

**Comment by JavaLionLi** [comment]
投票要投多久啊

**Comment by BaLaLaLs** [comment]
感觉节奏好慢

**Comment by funky-eyes** [comment]
> 感觉节奏好慢

还在孵化中的项目审核比较严格，所以节奏比较慢，社区目前已经开始了2.2的建设，但是2.1版本由于流程和合规问题还在审核中，需要耐心等待
The project under incubation has strict review processes, so progress is slow. The community has already begun construction for version 2.2. However, version 2.1 is still under review due to procedural and compliance issues, requiring patience.

**Comment by JavaLionLi** [comment]
这节奏 2.2开发完了感觉 2.1都发布不了
